dataloader:
  batch_size: 128
  sample_size: 256
  shuffle: true
  test_dataset:
    coefficient: 0.01
    params:
      data_root: ./Data/datasets/energy_data.csv
      distribution: geometric
      name: energy
      neg_one_to_one: true
      period: test
      proportion: 0.9
      save2npy: true
      seed: 123
      style: separate
      window: 24
    sampling_steps: 250
    step_size: 0.05
    target: Utils.Data_utils.real_datasets.CustomDatasetOURS
  train_dataset:
    params:
      data_root: /cfs/cfs-54d255b38/zomeryang/20250421_193157/Diffusion-TS/Data/train_data/85/train/Bobcat_warehouse_Charlie_start2000_720.csv
      name: energy
      neg_one_to_one: true
      period: train
      proportion: 0.85
      save2npy: true
      seed: 123
      window: 24
    target: Utils.Data_utils.real_datasets.CustomDataset
model:
  params:
    attn_pd: 0.0
    beta_schedule: cosine
    d_model: 96
    feature_size: 6
    kernel_size: 1
    loss_type: l1
    mlp_hidden_times: 4
    n_heads: 4
    n_layer_dec: 3
    n_layer_enc: 4
    padding_size: 0
    resid_pd: 0.0
    sampling_timesteps: 1000
    seq_length: 24
    timesteps: 1000
  target: Models.interpretable_diffusion.gaussian_diffusion.Diffusion_TS_ours
solver:
  base_lr: 1.0e-05
  ema:
    decay: 0.995
    update_interval: 10
  gradient_accumulate_every: 2
  max_epochs: 10000
  results_folder: CK/ours/85/train/Bobcat_warehouse_Charlie_start2000_720
  save_cycle: 2000
  scheduler:
    params:
      factor: 0.5
      min_lr: 1.0e-05
      patience: 5000
      threshold: 0.1
      threshold_mode: rel
      verbose: false
      warmup: 500
      warmup_lr: 0.0008
    target: engine.lr_sch.ReduceLROnPlateauWithWarmup
